theme: jekyll-theme-slate
highlighter: rouge
encoding: utf-8
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
repository: nanase/kf-elehoc
url: https://nanase.cc/kf-elehoc
title: けもフレ電子工作部
share-links-active:
  twitter: true
social-network-links:
  github: nanase
  twitter: nanase_coder
whitelist:
  - jekyll-github-metadata
plugins:
  - jekyll-github-metadata
